### ISSUE TITLE
Bot not working properly

### ISSUE THREAD

**Issue by tanay13** [LockedUp-Coders/meta#14]
After deploying the bot should deliver the message immediately if someone opens an issue or creates a pull request but sometimes i have to manually go to the delivery logs and select redeliver even if it shows its has been delivered .
<img width="544" alt="Screenshot (113)" src="https://user-images.githubusercontent.com/61361310/84364316-8da1a000-abed-11ea-9c94-0eb5b809623a.png">
In the body it is returning html doc instead it should return 'ok' . After clicking on redeliver , the message is sent by the bot . How to fix this so that i don't have to do this manually?

**Comment by YashKumarVerma** [comment]
Bot would take time to send first reply, the reason is that your glitch deploy "sleeps" after inactivity.
