### ISSUE TITLE
Create mascot for organization

### ISSUE THREAD

**Issue by YashKumarVerma** [LockedUp-Coders/meta#2]
Every team is incomplete without a mascot.

Create a simple (or complex if you wish) mascot for the team, so that we can use it for GitHub org. the profile picture and also as slack logo.

**Comment by V41SH** [comment]
I'll take a crack at this.

**Comment by V41SH** [comment]
This is what I came up with.

[LockedUpLogo](https://user-images.githubusercontent.com/53509994/84184730-82def200-aaab-11ea-86d9-c16f63f800f0.png)

**Comment by YashKumarVerma** [comment]
Good !

**Comment by YashKumarVerma** [comment]
Added !
![image](https://user-images.githubusercontent.com/14032427/84185234-524b8800-aaac-11ea-94f9-25fbef170a0c.png)

**Comment by dhairyaostwal** [comment]
@YashKumarVerma This is what I came up with
![Logo with Background](https://user-images.githubusercontent.com/50984984/84188505-57f79c80-aab1-11ea-9750-749c40e0c75a.png)

**Comment by adinalini** [comment]
Since the mascot has been finalised, should we close the issue?

**Comment by YashKumarVerma** [comment]
I think since we have two submissions, can someone merge the two ? Something like

 < lock >  would be cool I guess :smile: 
@dhairyaostwal  @V41SH

**Comment by adinalini** [comment]
![Lockedup](https://user-images.githubusercontent.com/28394580/84228111-c1080000-ab03-11ea-839f-ee795f717efb.png)
Here :)

**Comment by adinalini** [comment]
![Locked up](https://user-images.githubusercontent.com/28394580/84228397-8b174b80-ab04-11ea-9c1c-8da9c7ca3ddb.png)
In a square format

**Comment by adinalini** [comment]
Close this issue @YashKumarVerma

**Comment by V41SH** [comment]
@YashKumarVerma I think you can close this issue.
