### ISSUE TITLE
Setup templates for collaboration

### ISSUE THREAD

**Issue by YashKumarVerma** [LockedUp-Coders/meta#3]
Add the files like this project.

- GitHub issue template
- GitHub pr template
- Contributing guidelines/practices
- Code of conduct

**Comment by KarandeepSinghCoder** [comment]
Hi Yash. I would love to resolve this issue.

**Comment by adinalini** [comment]
Hey @KarandeepSinghCoder I have already added contributing guidelines in README.md so no need to write it again

**Comment by YashKumarVerma** [comment]
> Hey @KarandeepSinghCoder I have already added contributing guidelines in README.md so no need to write it again

could you check the function of contributing guidelines ? I think adding them to the readme is not the best thing.

**Comment by adinalini** [comment]
> > Hey @KarandeepSinghCoder I have already added contributing guidelines in README.md so no need to write it again
> 
> could you check the function of contributing guidelines ? I think adding them to the readme is not the best thing.

Doesn't label usage and 1 pr per issue thing come under contributing guidelines.
Will there be a separate contributing.md? If yes, then what should I keep in readme.md? Just a basic info on what this program is?

**Comment by YashKumarVerma** [comment]
> > > Hey @KarandeepSinghCoder I have already added contributing guidelines in README.md so no need to write it again
> > 
> > 
> > could you check the function of contributing guidelines ? I think adding them to the readme is not the best thing.
> 
> Doesn't label usage and 1 pr per issue thing come under contributing guidelines.
> Will there be a separate contributing.md? If yes, then what should I keep in readme.md? Just a basic info on what this program is?

I guess then we can have the file linked to a heading in readme.

**Comment by adinalini** [comment]
> I guess then we can have the file linked to a heading in readme.
Alrighty
