### ISSUE TITLE
Adapt new standard for github templates

### ISSUE THREAD

**Issue by YashKumarVerma** [LockedUp-Coders/meta#8]
**Actual Behaviour**
Adapt new changes by github

**Expected Behaviour**
We are using an old standard

**Steps to reproduce it**
Open a new issue. We do not see different sections to file bug request or feature request

**Screenshots of the issue**
NA

**Would you like to work on the issue?**
No

Tutorial: https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by adinalini** [comment]
I'll take this up
